name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: Pop!_OS
    steps:
    - name: hello wolrd !!
      run: echo Hello, world!
    - name: 디렉토리 !!
      run: ls -al
    - name: 파이썬 버전 출력!!
      run: python -V
